kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

steps:
  - name: Terraform FMT PR
    image: jmccann/drone-terraform:latest
    settings:
      root_dir: terraform
      actions:
        - fmt
      fmt_options:
        write: false
        diff: true
        check: true
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY_ID
      AWS_DEFAULT_REGION: "us-east-1"
    when:
      event:
      - pull_request

  - name: Terraform Plan
    image: jmccann/drone-terraform:latest
    settings:
      root_dir: terraform
      actions:
        - validate
        - plan
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY_ID
      AWS_DEFAULT_REGION: "us-east-1"
    when:
      event:
      - pull_request

  - name: Terraform FMT
    image: jmccann/drone-terraform:latest
    settings:
      root_dir: terraform
      actions:
        - fmt
      fmt_options:
        write: false
        diff: true
        check: true
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY_ID
      AWS_DEFAULT_REGION: "us-east-1"
    when:
      branch:
      - main
      event:
      - push
      - tag

  - name: Terraform Apply
    image: jmccann/drone-terraform:latest
    settings:
      root_dir: terraform
      actions:
        - validate
        - plan
        - apply
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY_ID
      AWS_DEFAULT_REGION: "us-east-1"
    when:
      branch:
      - main
      event:
      - push
      - tag
