kind: pipeline
type: docker
name: default

steps:
  - name: terraform
    image: jmccann/drone-terraform:5
    settings:
      plan: false
      vars:
        tf_backup_infra_state_bucket_name: kevcoxe-test-drone